### PR TITLE
Support Hashed Assets

### PR DESCRIPTION
**Pull request by mike-sheppard**
## Summary
1. These small tweaks hopefully simplify our checks as we're already gathering most of this info within `svg_collector()`, so we shouldn't need to check again. ✅ 

2. By saving the full file path in `svg_collector()` we can provide support for hashed assets eg. `arrow-left.524a72.svg` (we currently have this issue, nice to get a fix in for it!)  ✅ 

**Output of  `svg_collector()`**
```php
[
    "arrow left" => [
        "name"      => "arrow left",
        "filename"  => "arrow-left.524a72",
        "icon"      => "arrow-left.524a72.svg",
        "url"       => "/dist/editor/images/icons/admin-picker/arrow-left.524a72.svg",
        "path"      => "<OS_PATH>/<theme-name>/public/dist/editor/images/icons/admin-picker/arrow-left.524a72.svg"
    ],

    ...
]
```

## TODO/Further Suggestions

3. Also, might be better to save an `ID` (something like `sanitize_key($name)`) of the icon to the ACF field instead of the name? (not yet implemented, good to hear your thoughts on this @Levdbas — and while we're at it, do the title case transforms PHP side, either transform `ucwords($name)` or add an additional prop `title => ucwords($name)` + simplify js a bit more?  ✅ 

**Output of  `svg_collector()` using key**
```php
[
    "arrow-left" => [
        "key"       => "arrow-left",
        "title"     => "Arrow Left",
        "url"       => "<site_url>/dist/editor/images/icons/admin-picker/arrow-left.524a72.svg",
        "path"      => "<os_path>/<theme_name>/public/dist/editor/images/icons/admin-picker/arrow-left.524a72.svg"

         // + maybe we can remove these now?
        "name"      => "arrow left",
        "filename"  => "arrow-left.524a72",
        "icon"      => "arrow-left.524a72.svg",
       ...

```

### CODE REVIEW

**Comment by mike-sheppard** [comment]
Later tweaks/fixes
- [x] Fixed filters since the js svg array is now an object
- [x] Removed `name`, `filename` and `icon` from the svgs array (point 3 above)
- [x] ⚠️ Breaking Change: Saving sanitized key as ACF field value instead of 'name'

**Comment by Levdbas** [comment]
Hi @mike-sheppard , looks good, but what happens after this change on existing websites with field values saved? Will icons still appear "selected" for example? Maybe we can create something on the JS/php field side that will automatically will update/sanitize the value when not done already?

**Comment by mike-sheppard** [comment]
hey @Levdbas should work as it always has, but there will be a breaking change for any previous values that were saved unsanitized.

**Comment by mike-sheppard** [comment]
yeah that's not a bad shout on the conversion, will look into it!

**Comment by mike-sheppard** [comment]
@Levdbas just pushed up a potential fix, could you try it on an existing project please 🙏

**Comment by Levdbas** [comment]
Tested out main-dev after setting icons in an older version and looks good to me. 

afbeelding

**Comment by mike-sheppard** [comment]
Cool, added a test for the sanitised/unsanitised keys + tidied the acf field HTML markup out into a new view ✅

**Pull request merged**
